import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  typedRoutes: true,
  serverExternalPackages: ["@remotion/renderer", "webpack", "webpack-sources", "source-map"],
  outputFileTracingIncludes: {
    "/api/mobile-video/render": [
      "./remotion/**/*",
      "./components/SceneStage.tsx",
      "./components/CodeEditorModal.tsx",
      "./components/CodePreviewCard.tsx",
      "./components/AnimatedIconPlayer.tsx",
      "./components/EmojiAssetPicker.tsx",
      "./lib/mobileVideoRender.ts",
      "./lib/imageUpload.ts",
      "./lib/animatedFeatureIcons.ts",
      "./lib/sceneDefinitions.ts",
      "./lib/sceneTransitions.ts",
      "./node_modules/@remotion/bundler/dist/**/*",
      "./node_modules/@remotion/bundler/node_modules/webpack/**/*",
      "./node_modules/@remotion/bundler/css-loader/**/*",
      "./node_modules/@remotion/bundler/react-shim.js",
      "./node_modules/@remotion/bundler/favicon.ico",
      "./node_modules/@remotion/studio/dist/renderEntry.js",
      "./node_modules/@remotion/studio/dist/esm/renderEntry.mjs",
      "./node_modules/webpack/**/*",
      "./node_modules/webpack-sources/**/*",
      "./node_modules/source-map/**/*",
      "./node_modules/react/**/*",
      "./node_modules/react-dom/**/*",
      "./node_modules/remotion/**/*",
    ],
  },
  outputFileTracingExcludes: {
    "/*": [
      "./node_modules/.remotion/**/*",
      "./node_modules/@rspack/binding-win32-*/**/*",
      "./node_modules/@rspack/binding-darwin-*/**/*",
      "./node_modules/@rspack/binding-linux-arm64-*/**/*",
      "./node_modules/@remotion/compositor-win32-*/**/*",
      "./node_modules/@remotion/compositor-darwin-*/**/*",
      "./node_modules/@remotion/compositor-linux-arm64-*/**/*",
      "./node_modules/@esbuild/win32-*/**/*",
      "./node_modules/@esbuild/darwin-*/**/*",
      "./node_modules/@esbuild/linux-arm64/**/*",
    ],
    "/api/mobile-video/render": [
      "./node_modules/.remotion/**/*",
      "./node_modules/@remotion/compositor-win32-*/**/*",
      "./node_modules/@remotion/compositor-darwin-*/**/*",
      "./node_modules/@rspack/**/*",
      "./node_modules/@img/sharp-win32-*/**/*",
      "./node_modules/typescript/**/*",
      "./public/banner-themes/**/*",
      "./public/scene-previews/**/*",
      "./public/ffmpeg/**/*",
    ],
  },
};

export default nextConfig;
