import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  typedRoutes: true,
  outputFileTracingIncludes: {
    "/api/mobile-video/render": [
      "./scripts/render-mobile-video.cjs",
      "./remotion/**/*",
      "./node_modules/@remotion/bundler/**/*",
      "./node_modules/@remotion/renderer/**/*",
      "./node_modules/@remotion/media-parser/**/*",
      "./node_modules/@remotion/studio/**/*",
      "./node_modules/@remotion/studio-shared/**/*",
      "./node_modules/@rspack/**/*",
      "./node_modules/remotion/**/*",
      "./node_modules/esbuild/**/*",
      "./node_modules/@esbuild/**/*",
      "./node_modules/loader-utils/**/*",
      "./node_modules/postcss/**/*",
      "./node_modules/postcss-value-parser/**/*",
      "./node_modules/react/**/*",
      "./node_modules/react-dom/**/*",
      "./node_modules/react-refresh/**/*",
      "./node_modules/scheduler/**/*",
      "./node_modules/source-map/**/*",
      "./node_modules/webpack/**/*",
      "./node_modules/@webassemblyjs/**/*",
      "./node_modules/acorn/**/*",
      "./node_modules/acorn-import-phases/**/*",
      "./node_modules/browserslist/**/*",
      "./node_modules/chrome-trace-event/**/*",
      "./node_modules/enhanced-resolve/**/*",
      "./node_modules/es-module-lexer/**/*",
      "./node_modules/eslint-scope/**/*",
      "./node_modules/events/**/*",
      "./node_modules/glob-to-regexp/**/*",
      "./node_modules/graceful-fs/**/*",
      "./node_modules/loader-runner/**/*",
      "./node_modules/mime-db/**/*",
      "./node_modules/neo-async/**/*",
      "./node_modules/schema-utils/**/*",
      "./node_modules/tapable/**/*",
      "./node_modules/terser-webpack-plugin/**/*",
      "./node_modules/watchpack/**/*",
      "./node_modules/webpack-sources/**/*",
    ],
  },
};

export default nextConfig;
